import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';
import fs from 'fs';

interface DocumentChunk {
  document_name: string;
  content: string;
  metadata: {
    chunk_index: number;
    total_chunks?: number;
    pages?: number;
  };
}

async function directUpload() {
  const supabaseUrl = process.env.VITE_SUPABASE_URL;
  const supabaseKey = process.env.VITE_SUPABASE_ANON_KEY;

  if (!supabaseUrl || !supabaseKey) {
    throw new Error('Missing environment variables');
  }

  const supabase = createClient(supabaseUrl, supabaseKey);

  const chunksFile = './processed-chunks.json';

  if (!fs.existsSync(chunksFile)) {
    console.error('No processed-chunks.json file found.');
    return;
  }

  const chunks: DocumentChunk[] = JSON.parse(fs.readFileSync(chunksFile, 'utf-8'));

  console.log(`\n📤 Uploading ${chunks.length} chunks directly to database...`);
  console.log('Note: Embeddings will be generated by the edge function later.\n');

  const batchSize = 100;
  let uploadedCount = 0;

  for (let i = 0; i < chunks.length; i += batchSize) {
    const batch = chunks.slice(i, i + batchSize);

    const records = batch.map(chunk => ({
      document_name: chunk.document_name,
      content: chunk.content,
      metadata: chunk.metadata,
    }));

    try {
      const { data, error } = await supabase
        .from('document_chunks')
        .insert(records)
        .select();

      if (error) {
        console.error(`  ✗ Batch ${Math.floor(i / batchSize) + 1} failed:`, error.message);
      } else {
        uploadedCount += data.length;
        console.log(`  ✓ Batch ${Math.floor(i / batchSize) + 1}: ${uploadedCount}/${chunks.length} chunks`);
      }
    } catch (error: any) {
      console.error(`  ✗ Batch ${Math.floor(i / batchSize) + 1} error:`, error.message);
    }
  }

  console.log(`\n✅ Upload complete! Successfully uploaded ${uploadedCount} chunks`);
  console.log('\n⚠️  Note: Embeddings are NULL. You need to:');
  console.log('   1. Deploy the store-documents edge function');
  console.log('   2. Run a script to generate embeddings for existing chunks');
}

directUpload().catch(console.error);
